POST http://localhost:8080/api/policies HTTP/1.1
content-type: application/json

{
    "name": "Silver Auto Policy",
    "holder_first_name": "Erik",
    "holder_last_name": "Gross",
    "holder_account_id": "555",
    "is_active_policy": true,
    "has_active_claim": false,
    "effective_date": "2020-10-20T18:00:00.000Z",
    "termination_date": "2030-10-20T18:00:00.000Z"
}

###

GET http://localhost:8080/api/policies HTTP/1.1
content-type: application/json

###

GET http://localhost:8080/api/policies/5f90e1acf829950d28be00ee HTTP/1.1
content-type: application/json

###

PUT http://localhost:8080/api/policies/5f910695e57d68a7ec27e59e HTTP/1.1
content-type: application/json

{
    "name": "Bronze Auto Policy",
    "holder_last_name": "Johns"
}

###

DELETE http://localhost:8080/api/policies/5f90e1acf829950d28be00ee HTTP/1.1
content-type: application/json

###

DELETE http://localhost:8080/api/policies HTTP/1.1
content-type: application/json

###

GET http://localhost:8080/api/policies/active HTTP/1.1
content-type: application/json

###
###

GET http://localhost:8080/api/policies?holder_last_name=gross&holder_first_name=Erik